# Generated by Django 3.2.8 on 2022-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday_year',
            field=models.PositiveIntegerField(default=1998),
            preserve_default=False,
        ),
    ]
