# Generated by Django 4.1 on 2022-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthday_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday_year',
        ),
    ]
